// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
    TOPN(100, 'uber bookings')
	// Rand(100), total bookings,
	// IN TBILLEQ(100, 02, TREATAS(CALCULATETABLE('uber bookings')))
	// if(bookings.table)
	= RANDBETWEEN(1,10)
	
